export class Data {
  cmds = [
    'GetStatus',
    'GetCameraInfo',
    'GetRFInfo',
    'UpdateOrCreateCamera',
    'UpdateRFSensor',
    'UpdateJammer',
    'JammerTimmer',
    'CreateCluster',
    'UpdateCluster',
    'DeleteCamera',
    'DeleteCluster',
    'SetExclZone',
    'SetBlurZone',
    'RestartCamera',
    'RestartRemora',
    'ReconnectJammer',
    'ActivateProtocol',
    'DeactivateProtocol',
    'ChangeConfirmationCt',
    'SetWifiThreat',
    'DeleteWifiThreat',
    'DeactivatedThreats',
    'SetJammerChannels',
    'ExportDatabase',
    'ExportLogs',
    'SaveData',
    'ExportTables',
    'ImportTables',
    'Ping',
    'CreateScenario',
    'UpdateScenario',
  ];

  payload = [
    {},
    {
      camera: 'xx:xx:xx:xx:xx:xx',
    },
    {
      rfSensor: 'xx:xx:xx:xx:xx:xx',
    },
    {
      label: 'camera label',
      serial: 'xx:xx:xx:xx:xx:xx',
      activated: 1,
      status: 'Running',
      streamPort: 123,
      bearing: 70,
      angle: 80,
      radius: 150,
      coordinateLat: 1.5678,
      coordinateLong: 1.45678,
      tilt: 20,
      password: 'pass',
      user: 'user',
      model: 'the model',
      subtractorHistory: 50,
      minPoints: 6,
      minArea: 10,
      vMorphology: 50,
      hMorphology: 50,
      blurPolygons: 'polygon_1$polygon_2$...',
      polygons: 'polygon_1$polygon_2$...',
      droneIndex: 70,
      sectorId: 1,
    },
    {
      bearing: 0,
      port: 6667,
      clusterId: '0',
      displayDebug: 0,
      gain: 70,
      ip: '127.0.0.1',
      label: 'RM3000',
      model: 'RMMOCK',
      serial: 'dddd',
      sensorId: 'RFSensor_9',
      tilt: 90,
      coordinateLat: 2.2,
      coordinateLong: 2.3,
    },
    {
      jammerId: 'jammer_1',
      serial: 'ac:cc:b0:f8:6d:ec',
      ip: '192.168.0.11',
      label: 'Jammer 2.4GHz',
      model: 'SESP',
      port: '4444',
      clusterId: '1',
    },
    {
      jammerTimer: 10,
    },
    {
      clusterLabel: 'DF cluster',
      coordinateLat: 48.77783203125,
      coordinateLong: 2.243993043899536,
      sectorId: 1,
      taskType: 'JammerS',
    },
    {
      activated: true,
      clusterId: '1',
      coordinateLat: 48.77783203125,
      coordinateLong: 2.243993043899536,
      freq2450: 4095,
      freq1300: 0,
      freq433: 0,
      freq5800: 1,
      freq865: 0,
      freq915: 0,
      wifi: 4095,
      sectorId: 1,
      clusterLabel: 'cluster A',
      antennaType: 'SRC9',
      taskType: 'Hydra100',
      bearingOffset: 0,
      radius: 2000,
      successiveAlerts: 0,
      saveImg: 0,
      saveIQ: 0,
      saveDataFile: 0,
      saveIfAlert: 0,
      saveDataPrefix: '',
      jammerAutostart: 0,
      scenarioId: 2,
      angle: 360,
    },
    {
      serial: 'xx:xx:xx:xx:xx:xx',
    },
    {
      clusterId: '1',
    },
    {
      camera: 'xx:xx:xx:xx:xx:xx',
      polygons: 'x1,y1;x2,y2;x3,y3$x1,y1;x2,y2;x3,y3;x4,y5',
    },
    {
      camera: 'xx:xx:xx:xx:xx:xx',
      polygons: 'x1,y1;x2,y2;x3,y3$x1,y1;x2,y2;x3,y3;x4,y5',
    },
    {
      serial: 'xx:xx:xx:xx:xx:xx',
    },
    {
      sensorId: 'RFSensor_2',
    },
    {
      jammerId: 'jammer_1',
    },
    {
      protocolName: 'lightbridge',
    },
    {
      protocolName: 'lightbridge',
    },
    {
      protocolName: 'lightbridge',
      increase: 1,
      decrease: 0,
      setValue: 4,
    },
    {
      name: 'parrot',
      type: 'mac',
      value: 'xx:xx:xx:xx:xx',
      permission: 'deny',
    },
    {
      id: 1,
      mac: 'xx:xx:xx:xx:xx',
    },
    [
      { deactivatedProtocols: 'lightbridge2;ocusync' },
      { wifiWhiteList: 'bebop2;10:ac:5f:3c' },
      { withConfirmation: 'devo=3;lightbridge2video=1' },
    ],
    [
      [{ channel: 1 }, { status: 1 }, { login: 'admin' }],
      [{ channel: 2 }, { status: 1 }, { login: 'admin' }],
    ],
    [{ id: 'id' }, { path: 'path' }],
    [{ id: 'id' }, { path: 'path' }],
    {
      id: '1',
      saveImg: true,
      saveDataFile: false,
      saveDataPrefix: 'myPrefix',
      duration: 40,
      saveIQ: true,
    },
    {
      RFProtocols: [
        {
          activated: 0,
          confirmationCt: 0,
          hasPreamble: 0,
          minScore: 20,
          name: 'bayang',
        },
        {
          activated: 0,
          confirmationCt: 0,
          hasPreamble: 0,
          minScore: 15,
          name: 'cx10',
        },
      ],
      WifiThreat: [],
      enableSSID: true,
      jammerTimer: 10,
    },
    {},
    {},
    {
      label: 'activate all',
      frequencyResponse: 1,
      powerOutputUpDown: 100,
      gnssResponse: 1,
      powerOutputGNSS: 50,
      duration: 60,
      deleted: 0,
    },
    {
      label: 'activate all',
      frequencyResponse: 1,
      powerOutputUpDown: 100,
      gnssResponse: 1,
      powerOutputGNSS: 50,
      duration: 60,
      deleted: 0,
    },
  ];
}
